services:
  postgres:
    image: postgres:16
    container_name: homeinventory-postgres
    environment:
      POSTGRES_DB: homeinventory
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - hi_pgdata:/var/lib/postgresql/data

volumes:
  hi_pgdata:
